dap-web:
  image: nginx:1.17
  ports:
    - "205.202.242.13:80:80"
    - "205.202.242.13:443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/ssl
    - ./public:/usr/share/nginx/html
    - /var/log/docker/dap:/var/log/nginx
  command: [nginx, '-g', 'daemon off;']
